### ISSUE TITLE
busctl cannot activate service rs.wl-gammarelay

### ISSUE THREAD

**Issue by Cornflames** [MaxVerevkin/wl-gammarelay-rs#19] opened 2024-03-03 10:39 UTC
When I try to use *wl-gammarelay-rs* in the terminal I get the following error message:
```
$ busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 5000
Failed to set property Temperature on interface rs.wl.gammarelay: The name ist not activatable
```
This seems to be in line with the following error with introspection:
```
$ busctl --user introspect rs.wl-gammarelay / rs.wl.gammarelay
Failed to introspect object / of service rs.wl-gammarelay: The name is not activatable
```
Because I'm very unfamiliar with using dbus and because running the above commands with sudo throws that `$DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR are not defined`, this is likely a **problem with my dbus** rather than with wl-gammarelay-rs. In addition, my system does not know the `wl-gammarelay-rs ` cli, so my installation or setup might be incomplete?

I'm sorry to opening an issue, but I am a beginner and common dbus problem solving techniques like described [here](https://askubuntu.com/questions/1374347/error-running-systemd-as-user-failed-to-connect-to-bus-dbus-session-bus-addr) didn't work for me. So I would be very thankful for any help!

Note: My system is archlinux and I run the Hyprland window manager.

**Comment by MaxVerevkin** [comment] 2024-03-03 10:50
> my system does not know the wl-gammarelay-rs cli, so my installation or setup might be incomplete?

Yes. Which method of installation did you use? If `cargo install ...`, then you need to add `~/.cargo/bin` to your `PATH`. There is also an AUR package.

You have to launch `wl-gammarelay-rs` somehow. In your hyprland config for example.

I am not familiar with DBus activation, but presumably if #17 gets implemented, you will not have to launch it manually.

> with sudo throws that $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR are not defined, this is likely a problem with my dbus rather than with wl-gammarelay-rs

No, no, don't run busctl with sudo.

**Comment by Cornflames** [comment] 2024-03-03 11:00
I installed it with `cargo install wl-gammarelay-rs --locked` from source. Adding `~/.cargo/bin` to my `PATH` worked fine, now I find `wl-gammarelay-rs`!
I will try to do some more research about DBus activation. However, thank you for your help so far!

**Comment by MaxVerevkin** [comment] 2024-03-18 06:41
I will close this as a duplicate of #17

**Closed by MaxVerevkin** 2024-03-18 06:41 UTC
